# Generated by Django 4.2.7 on 2023-12-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
