# Generated by Django 4.2.7 on 2023-12-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
