# Generated by Django 4.2.7 on 2023-12-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_designation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
