# Generated by Django 4.2.7 on 2023-12-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_addclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prodcuctcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.IntegerField()),
                ('productname', models.CharField(max_length=200)),
            ],
        ),
    ]
