# Generated by Django 4.2.7 on 2023-12-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_category_prodcuctcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcuctcategory',
            name='catid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.category'),
        ),
    ]
