# Generated by Django 4.2.7 on 2023-12-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
